 version: "3"
 services:
    ssr:
      build:
        context: ./
        dockerfile: ./Dockerfile
      ports:
      - "3000:3000"
    static:
      build:
        context: ./
        dockerfile: ./Dockerfile-static
      ports:
      - "8080:80"
